### Variáveis globais
# @baseUrl = http://localhost/fv/server_driven_ui_php
@baseUrl = http://192.168.100.33/fv/server_driven_ui_php
# ou @baseUrl = http://seu-dominio.com

### GET Request
### Listar todos os produtos
GET {{baseUrl}}/index.php/produtos HTTP/1.1
Content-Type: application/json

### Buscar produto específico
GET {{baseUrl}}/index.php/produtos/4 HTTP/1.1
Content-Type: application/json

### Listar todas as categorias
GET {{baseUrl}}/index.php/categorias HTTP/1.1
Content-Type: application/json

### Buscar categoria específica
GET {{baseUrl}}/index.php/categorias/2 HTTP/1.1
Content-Type: application/json

### POST Request
POST {{baseUrl}}/index.php/produtos HTTP/1.1
Content-Type: application/json

{
    "nome": "Produto Teste 5",
    "preco": 99.99,
    "descricao": "Descrição do produto 05",
    "categoria": "ferramenta"
}

### PUT Request
PUT {{baseUrl}}/index.php HTTP/1.1
Content-Type: application/json
]
{
    "nome": "Produto Atualizado",
    "preco": 149.99,
    "descricao": "Descrição atualizada"
}

### DELETE Request
DELETE {{baseUrl}}/produtos/1 HTTP/1.1
Content-Type: application/json


############################################################
############################################################
############################################################

### Buscar tela
GET {{baseUrl}}/index.php/tela/1 HTTP/1.1
Content-Type: application/json

### Criar nova tela
POST {{baseUrl}}/index.php/tela HTTP/1.1
Content-Type: application/json

{
    "nome": "Tela Principal",
    "descricao": "Tela inicial do aplicativo",
    "components": [
        {
            "key": "MyComponent",
            "value": {
                "text": "Hello World"
            }
        },
        {
            "key": "CraftDTextView",
            "value": {
                "text": "Hello World CraftD",
                "textSize": "40",
                "textColorHex": "#D977EB"
            }
        },
        {
            "key": "CraftDButton",
            "value": {
                "text": "Some Action like this :)",
                "align": "RIGHT",
                "textAlign": "CENTER",
                "textAllCaps": true,
                "textSize": "20",
                "textColorHex": "#FFFFFF",
                "backgroundHex": "#2fa003",
                "actionProperties": {
                    "deeplink": "CraftDview://any",
                    "analytics": {
                        "category": "hello",
                        "action": "world",
                        "label": "everywhere"
                    }
                }
            }
        }
    ]
}

### Login

POST {{baseUrl}}/index.php/login HTTP/1.1
Content-Type: application/json

{
    "email": "nmaycon304@gmail.com",
    "password": "12345678A"
}